
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER KH_jsy IDENTIFIED BY "oracle_jsy123A";

GRANT RESOURCE, CONNECT TO KH_jsy;

ALTER USER KH_jsy DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;
